New Velocloud Edge Metrics
kentik/snmp-profiles pull request #713
Opened 2023-10-31 15:32 UTC by Mamoon-Khan

Added new metric in VeloCloud SNMP profile

2023-10-31 16:11 UTC, thezackm commented
thank you for your submission @Mamoon-Khan 

please update this PR to change the individual OIDs listed from the scalar functions they are now into a table configuration for the [vceLinkTable](https://mibs.observium.org/mib/VELOCLOUD-EDGE-MIB/#vceLinkTable) that these all look to be members of.

you can see an example of how to pivot these into a table configuration with `metric_tags` here: https://github.com/kentik/snmp-profiles/blob/ccb1df47a5068a59fb3e3765746524e0286252e7/profiles/kentik_snmp/_template.yml#L41-L78

2023-10-31 17:16 UTC, thezackm requested changes
please redact the CSV file from this PR

2023-10-31 17:16 UTC, thezackm commented on Velo-Static-Circuits-2023-10-31.csv
please remove this file

2023-11-01 13:00 UTC, Mamoon-Khan commented on Velo-Static-Circuits-2023-10-31.csv
done

2023-11-01 16:02 UTC, thezackm requested changes
a few more edits; looks a lot better

2023-11-01 16:02 UTC, thezackm commented on profiles/kentik_snmp/velocloud/velocloud-edge.yml
> +        OID: 1.3.6.1.4.1.45346.1.1.2.3.2.2.1.33
this is an enumerated OID; as it sits right now the only value returned will be an integer; you'll want to add the enumeration of `VceLinkStateType` from [the MIB file](https://jira.observium.org/secure/attachment/19423/VeloCloudEdge510-EnterpriseMib.txt) to make this human-readable.

```yaml
metric_tags:
  - tag: link_state
    column:
      name: vceLinkState
      oid: 1.3.6.1.4.1.45346.1.1.2.3.2.2.1.34
      enum:
        initial: 1
        dead: 2
        unusable: 3
        quiet: 4
        standby: 5
        unstable: 6
        stable: 7
        unknown: 8
```

2023-11-01 21:48 UTC, thezackm approved these changes
🚀  thanks for the submission!

2023-11-01 21:48 UTC, merged