Update cisco-nexus.yml
kentik/snmp-profiles pull request #727
Opened 2023-11-20 10:55 UTC by al3kh

Updated with proposed changes
@thezackm Hi, I am unable to find table OID for peertable
https://cisco.github.io/cisco-mibs/supportlists/nexus9000/Nexus9000MIBSupportList.html

2023-11-20 16:31 UTC, thezackm requested changes
The linked doc only shows the direct OIDs (scalar and tabular rows) supported, it isn't a reflection of [the MIB](https://mibs.observium.org/mib/CISCO-BGP4-MIB/#cbgpPeer3Table) which shows the following:

```
cbgpPeer3Table: 1.3.6.1.4.1.9.9.187.1.2.9
  - cbgpPeerEntry: 1.3.6.1.4.1.9.9.187.1.2.9.1
    - cbgpPeer3VrfId: 1.3.6.1.4.1.9.9.187.1.2.9.1.1
    - cbgpPeer3Type: 1.3.6.1.4.1.9.9.187.1.2.9.1.2
    - cbgpPeer3RemoteAddr: 1.3.6.1.4.1.9.9.187.1.2.9.1.3
    - cbgpPeer3VrfName: 1.3.6.1.4.1.9.9.187.1.2.9.1.4
    - cbgpPeer3State: 1.3.6.1.4.1.9.9.187.1.2.9.1.5
```

you can also reference the [actual MIB file](https://raw.githubusercontent.com/cisco/cisco-mibs/main/v2/CISCO-BGP4-MIB.my) which shows this table was added in `REVISION "202004140000Z"`

2023-11-20 16:31 UTC, thezackm commented on profiles/kentik_snmp/cisco/cisco-nexus.yml
> +        OID: 1.3.6.1.4.1.9.9.187.1.2.9.1.2
adding notes from original PR, which are still relevant:
--
this should be a tabular collection from the `cbgpPeer3Table` in the MIB. `cbgpPeer3State` would be the only metric and the other 4 OIDs should be under `metric_tags`* 


*including `cbgpPeer3Type`, this is a non-volatile metric and should be fine as a decoration on the status (we update the `metric_tag` values every 30min)

2023-11-22 09:01 UTC, al3kh commented
@thezackm please verify i have updated the table. thanks

2023-11-29 14:27 UTC, thezackm approved these changes

2023-11-29 14:27 UTC, merged