Update a10-thunder.yml
kentik/snmp-profiles pull request #736
Opened 2024-01-02 16:41 UTC by al3kh

Added HA OIDs
@thezackm can you please approve

2024-01-05 13:13 UTC, al3kh commented
@thezackm hi, did you get a chance to take a look

2024-01-08 12:10 UTC, al3kh commented
@Mesverrum hi, can you please approve this. thanks

2024-01-08 18:21 UTC, thezackm requested changes
@al3kh - please see changes requested

2024-01-08 18:21 UTC, thezackm commented on profiles/kentik_snmp/a10_networks/a10-thunder.yml
> +        OID: 1.3.6.1.4.1.22610.2.4.3.17.2.2.1
the `*Entry` field in a MIB table is a placeholder for our needs and should not be part of this profile; please remove.

2024-01-08 18:21 UTC, thezackm commented on profiles/kentik_snmp/a10_networks/a10-thunder.yml
> +        OID: 1.3.6.1.4.1.22610.2.4.3.17.2.2.1.1
this is a non-volatile ID field (similar to a name) and should be used as a `metric_tag` value for this table

2024-01-08 19:10 UTC, al3kh commented
@thezackm Hi, made the requested changes.

2024-01-09 18:33 UTC, thezackm requested changes
@al3kh - one more small edit to move the `metric_tag` into the proper section

2024-01-09 18:33 UTC, thezackm commented on profiles/kentik_snmp/a10_networks/a10-thunder.yml
> +      OID: 1.3.6.1.4.1.22610.2.4.3.17.2.2.1.1
@al3kh - this needs to be targeted to the table; this `metric_tags` section is the global one that applies to the entire profile. There are examples of the correct indentation level and syntax throughout this profile; the first is on lines 179-183.

at a high level:

```yaml
metrics:
  - MIB: $MIB_NAME
    table: ... # table overview
    symbols: ... # metrics to collect from this table
    metric_tags: ... # attributes to decorate on top of the symbols defined in this table
...

# global metric_tags that apply to all scalar OIDs in this profile
metric_tags: ...
```

2024-01-12 14:38 UTC, thezackm approved these changes

2024-01-12 14:38 UTC, merged