Update cisco-asa.yml
kentik/snmp-profiles pull request #741
Opened 2024-01-18 13:13 UTC by al3kh

Updated Memory OIDs. @thezackm can you please approve

2024-01-24 16:34 UTC, al3kh commented
@thezackm, we noticed that mempooltype is 10 i.e. virtual memory. so we can go with the better one

2024-01-24 17:21 UTC, thezackm requested changes

2024-01-24 17:21 UTC, thezackm commented on profiles/kentik_snmp/cisco/cisco-asa.yml
> +    symbols:
@al3kh - looks good; this needs to be updated to the MIB table type (right now they are all scalar); otherwise the syntax looks right

2024-01-31 13:40 UTC, al3kh commented
@thezackm hi, made changes as requested

2024-02-01 18:53 UTC, thezackm approved these changes

2024-02-01 18:53 UTC, merged