Add OIDs for call volume to cisco-asr profile
kentik/snmp-profiles pull request #752
Opened 2024-02-20 20:05 UTC by pkanakaraj-sf

2024-02-20 22:52 UTC, thezackm requested changes
both of these metrics are part of the [cvCallVolIfTable](https://mibs.observium.org/mib/CISCO-VOICE-DIAL-CONTROL-MIB/#cvCallVolIfTable) and need to be setup as a MIB table. Based on the description of the table: 

>This table represents the information about the usage of an IP interface in a voice gateway for voice media calls. This table has a sparse-dependent relationship with ifTable. There exists an entry in this table, for each of the  entries in ifTable where ifType is one of 'ethernetCsmacd' and 'softwareLoopback'.

you should setup a `metric_tag` section on the table using the `IF-MIB` to pull in the interface details. [Example here](https://github.com/kentik/snmp-profiles/blob/7694cd65a24e8ae35ad334209d33e041adf7731e/profiles/kentik_snmp/_general/if-mib.yml#L80-L345)

2024-03-04 08:02 UTC, pkanakaraj-sf commented
Updated as suggested. Please review and let me know if any more changes are required. Thanks!

2024-03-04 16:26 UTC, thezackm requested changes
small change needed on the `metric_tag`

2024-03-04 16:26 UTC, thezackm commented on profiles/kentik_snmp/cisco/cisco-asr.yml
> +        table: ifTable
these 2 lines are unnecessary in a `metric_tag` configuration. see [this sample](https://github.com/kentik/snmp-profiles/blob/2f640c2f8202c491e11bcdc916ccd5b07343d9e2/profiles/kentik_snmp/cisco/cisco-all-devices.yml#L68-L73) for an example of calling the `IF-MIB` from a table in the `CISCO-IF-EXTENSION-MIB`

2024-03-04 18:31 UTC, pkanakaraj-sf commented
@thezackm updated. Thanks for the guidance!

2024-03-04 18:41 UTC, thezackm approved these changes

2024-03-04 18:41 UTC, merged